apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: loki
    targetRevision: 6.29.0
    helm:
      values: |
        write:
          replicas: 1
        read:
          replicas: 1
        backend:
          replicas: 1
        loki:
          useTestSchema: true
          commonConfig:
            replication_factor: 1
          auth_enabled: false
        test:
          enabled: false
        storage:
          type: filesystem
        minio:
          enabled: true
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
