apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-storefront-bff
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
      targetRevision: feat/add-argocd-apps
      path: k8s/charts/storefront-bff
      helm:
        valueFiles:
          - values.yaml
          - $values/k8s/deploy/staging/values-staging-override.yaml
        parameters:
          - name: backend.image.repository
            value: ghcr.io/nashtech-garage/yas-storefront-bff
    - repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
      targetRevision: feat/add-argocd-apps
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
