apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-storefront-ui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
      targetRevision: main
      path: k8s/charts/storefront-ui
      helm:
        valueFiles:
          - values.yaml
          - $values/k8s/deploy/staging/values-staging-override.yaml
          - $values/k8s/deploy/staging/services/storefront-ui.yaml
    - repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
