apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-swagger-ui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
      targetRevision: main
      path: k8s/charts/swagger-ui
      helm:
        valueFiles:
          - values.yaml
          - $values/k8s/deploy/staging/values-staging-override.yaml
          - $values/k8s/deploy/staging/services/swagger-ui.yaml
        parameters:
          - name: ingress.host
            value: api.staging.yas.local.com
    - repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
