apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: yas-dev-public-gateway
  namespace: yas-dev
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - storefront.dev.yas.local.com
        - backoffice.dev.yas.local.com
        - api.dev.yas.local.com
        - identity.yas.local.com
