apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: storefront-public-routes
  namespace: yas-dev
spec:
  hosts:
    - storefront.yas.local.com
  gateways:
    - yas-dev-public-gateway
  http:
    - route:
        - destination:
            host: storefront-bff
            port:
              number: 80
