apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: swagger-public-routes
  namespace: yas-dev
spec:
  hosts:
    - api.yas.local.com
  gateways:
    - yas-dev-public-gateway
  http:
    - match:
        - uri:
            prefix: /swagger-ui
      route:
        - destination:
            host: yas-dev-swagger-ui
            port:
              number: 8080
