apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: swagger-public-routes
  namespace: yas-staging
spec:
  hosts:
    - api.staging.yas.local.com
  gateways:
    - yas-staging-public-gateway
  http:
    - match:
        - uri:
            prefix: /media
      route:
        - destination:
            host: media
            port:
              number: 80
    - match:
        - uri:
            prefix: /swagger-ui
      route:
        - destination:
            host: yas-staging-swagger-ui
            port:
              number: 8080
