ui:
  image:
    repository: docker.io/tranan205/yas-storefront
    tag: latest
  nameOverride: storefront-ui
  fullnameOverride: storefront-ui
#  extraVolumes:
#    - name: storefront-env-production
#      configMap:
#        name: storefront-env-production-configmap
#        items:
#          - key: .env.production
#            path: .env.production
#  extraVolumeMounts:
#    - name: storefront-env-production
#      mountPath: /app/.env.production
#      readOnly: true
#      subPath: .env.production
  extraEnvs:
    - name: API_BASE_PATH
      value: http://storefront.yas.local.com/api
    - name: INTERNAL_API_BASE_PATH
      value: http://storefront-bff/api
  hostAliases:
    - ip: "10.0.99.80"
      hostnames:
        - storefront.yas.local.com
        - backoffice.yas.local.com
        - api.yas.local.com
        - identity.yas.local.com
  ingress:
    enabled: false

#storefrontEnvProduction: |
#  API_BASE_PATH=http://storefront.yas.local.com/api
