apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-cart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
    targetRevision: main
    path: k8s/charts/cart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: backend.image.repository
          value: ghcr.io/nashtech-garage/yas-cart
        - name: backend.image.tag
          value: latest
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
