apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
  namespace: observability
spec:
  type: ExternalName
  externalName: yas-staging-loki-gateway.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: observability
spec:
  type: ExternalName
  externalName: yas-staging-tempo.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: observability
spec:
  type: ExternalName
  externalName: yas-staging-prometheus-grafana.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-prometheus-prometheus
  namespace: observability
spec:
  type: ExternalName
  externalName: yas-staging-prometheus-kub-prometheus.observability.svc.cluster.local
