apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-dev-istio-routing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
    targetRevision: main
    path: k8s/deploy/dev/istio-routing
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yas-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
