apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-dev-tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: tempo
    targetRevision: 1.19.0
    helm:
      values: |
        tempo:
          metricsGenerator:
            enabled: true
            remoteWriteUrl: "http://prometheus-kube-prometheus-prometheus:9090/api/v1/write"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
