apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-dev-opentelemetry-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    chart: opentelemetry-operator
    targetRevision: 0.118.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
