apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-dev-swagger-ui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
      targetRevision: main
      path: k8s/charts/swagger-ui
      helm:
        valueFiles:
          - values.yaml
          - $values/k8s/deploy/dev/values-dev-override.yaml
        parameters:
          - name: image.repository
            value: swaggerapi/swagger-ui
          - name: image.tag
            value: v4.16.0
          - name: ingress.host
            value: api.yas.local.com
    - repoURL: "https://github.com/xyberr81/CSC11007-Lab.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yas-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
